In [5]:
a='34.54'
id(a)

2098079264560

In [6]:
type(a)

str

In [7]:
a=18
id(a)

2097993837392

In [8]:
import numpy as np

In [9]:
import sys


In [10]:
l1=range(1000)

In [11]:
print(len(l1)*sys.getsizeof(5))

28000


In [12]:
a1=np.arange(1000)

In [13]:
print(a1.size*a1.itemsize)

4000


In [14]:
size=1000
l1=range(size)
l2=range(size)

In [15]:
a1=np.arange(size)
a2=np.arange(size)

In [16]:
import time

In [23]:
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("List took:",(time.time()-start)*1000)

List took: 0.0


In [24]:
start=time.time()
result=[(x,y) for x,y in zip(l1,l2)]
print("List took:",(time.time()-start)*1000)

List took: 0.9908676147460938


In [25]:
start=time.time()
result=a1+a2
print("Ndarray:",(time.time()-start)*1000)

Ndarray: 0.0


In [26]:
#Numpy

In [29]:
l1=[1,2,3,4,5]
print(l1)
print(type(l1))

[1, 2, 3, 4, 5]
<class 'list'>


In [32]:
a=np.asarray(l1)
a

array([1, 2, 3, 4, 5])

In [33]:
type(a)

numpy.ndarray

In [35]:
b=np.array([10,20,30,40,50])
b.ndim

1

In [36]:
b.shape

(5,)

In [38]:
b.itemsize #size of itmes here  interger

4

In [39]:
b.size #no of elements in the array

5

In [40]:
b.dtype

dtype('int32')

In [41]:
a2=np.array([1,2,3,4,5],dtype=np.float64)

In [42]:
a2

array([1., 2., 3., 4., 5.])

In [43]:
arr=np.array([10,20,30,40,50])
print(arr.dtype)
float_arr=arr.astype(np.float64)
print(arr.dtype)

int32
int32


In [45]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [48]:
np.random.random((3,5))

array([[0.16357358, 0.77845611, 0.31027843, 0.36346154, 0.5917066 ],
       [0.12677563, 0.36948728, 0.54549344, 0.54228381, 0.11847205],
       [0.70551262, 0.7054853 , 0.49218432, 0.31551188, 0.73347318]])

In [50]:
np.random.randn(1,2)

array([[-0.46031934,  0.14549417]])

In [52]:
c=np.random.choice(('a','b','c'))
c

'b'

In [54]:
a3=np.linspace(1,2,1000)
a3

array([1.        , 1.001001  , 1.002002  , 1.003003  , 1.004004  ,
       1.00500501, 1.00600601, 1.00700701, 1.00800801, 1.00900901,
       1.01001001, 1.01101101, 1.01201201, 1.01301301, 1.01401401,
       1.01501502, 1.01601602, 1.01701702, 1.01801802, 1.01901902,
       1.02002002, 1.02102102, 1.02202202, 1.02302302, 1.02402402,
       1.02502503, 1.02602603, 1.02702703, 1.02802803, 1.02902903,
       1.03003003, 1.03103103, 1.03203203, 1.03303303, 1.03403403,
       1.03503504, 1.03603604, 1.03703704, 1.03803804, 1.03903904,
       1.04004004, 1.04104104, 1.04204204, 1.04304304, 1.04404404,
       1.04504505, 1.04604605, 1.04704705, 1.04804805, 1.04904905,
       1.05005005, 1.05105105, 1.05205205, 1.05305305, 1.05405405,
       1.05505506, 1.05605606, 1.05705706, 1.05805806, 1.05905906,
       1.06006006, 1.06106106, 1.06206206, 1.06306306, 1.06406406,
       1.06506507, 1.06606607, 1.06706707, 1.06806807, 1.06906907,
       1.07007007, 1.07107107, 1.07207207, 1.07307307, 1.07407

In [55]:
a=np.arange(12)

In [56]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
a=a.reshape((4,3))

In [61]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
a=a.ravel() #flattening the array(make it 1D)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
a.reshape((1,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [72]:
a.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [66]:
a.min()

0

In [68]:
a.max()

11

In [69]:
a.sum()

66

In [76]:
a.sum(axis = 0)

66

In [78]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [79]:
a.mean()

5.5

In [81]:
a.mean()

5.5

In [85]:
a=np.median(a)
a

5.5

In [86]:
a=np.array([1,2,3,4,4,5])
c=np.unique(a)
print(c)

[1 2 3 4 5]


In [87]:
a=np.array([1,2,3,4,5])
print(max(a))
print(np.argmax(a)) #index of highest value

5
4


In [88]:
a.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [89]:
a.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

In [90]:
a.var()

2.0

In [91]:
a.std()

1.4142135623730951

#Pandas

In [1]:
import pandas as pd
import numpy as np

In [3]:
l1=[1,2,3,4,5,6,7,8,9,10]
s=pd.Series(l1)
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [4]:
type(s)

pandas.core.series.Series

In [9]:
s1=pd.Series([100,89,67,23],index=['A','B','C','D'])
print(s1)

A    100
B     89
C     67
D     23
dtype: int64


In [12]:
d={'A':100,'B':89,"C":65,'D':90}
s=pd.Series(d)
s

A    100
B     89
C     65
D     90
dtype: int64

s*3

In [13]:
s*3

A    300
B    267
C    195
D    270
dtype: int64

In [14]:
s>65

A     True
B     True
C    False
D     True
dtype: bool

In [15]:
s.isnull()

A    False
B    False
C    False
D    False
dtype: bool

In [21]:
d=[1,3,4,5,6]
df=pd.DataFrame(d,index=['A','B','C','D','E'])
df

0
A  1
B  3
C  4
D  5
E  6

In [22]:
items=[["phone",2000],["Tv",1500]]
pdf=pd.DataFrame(items)
pdf

0     1
0  phone  2000
1     Tv  1500

In [23]:
df=pd.DataFrame(items,index=["Nokia","Apple"],columns=['Item',"Price"])
df

Item  Price
Nokia  phone   2000
Apple     Tv   1500

In [24]:
#CSV usinf pandas

In [25]:
data=pd.read_csv("Jobsearchdata.csv")
print(data)

                 Name  Age Qualification         Stream      Title  \
0      Neon Prabhakar   22          Bcom       Commerce  Executive   
1    R Gopalakrishnan   23           BBA  Administratio  Executive   
2         Pratik Kala   22           LLB         Lawyer   Advocate   
3         Nanda Kumar   24           BSc       Software  Developer   
4           Siju John   25           MCA       Software  Developer   
..                ...  ...           ...            ...        ...   
83       Jesfy Joseph   24           BSc       Software  Developer   
84            Sanulal   25           MCA       Software  Developer   
85            Syamlal   27           BBA  Administratio  Executive   
86  Sreeram Devarajan   27           MBA  Administratio    Manager   
87           Usha Raj   25          MBBS       Medicine     Doctor   

    Experience  Salary                                             Adress  \
0            1   12000  East Kadungallur, Near Uc Colleage Desom Ernak...   
1    

In [26]:
data.shape

(88, 9)

In [27]:
data.head(10)

Name  Age Qualification         Stream       Title  Experience  \
0    Neon Prabhakar   22          Bcom       Commerce   Executive           1   
1  R Gopalakrishnan   23           BBA  Administratio   Executive           2   
2       Pratik Kala   22           LLB         Lawyer    Advocate           1   
3       Nanda Kumar   24           BSc       Software   Developer           3   
4         Siju John   25           MCA       Software   Developer           4   
5         M K Shaji   27           BBA  Administratio   Executive           6   
6              Anas   27           MBA  Administratio     Manager           6   
7    Joshy Kuruvila   31          MBBS       Medicine      Doctor          10   
8  Jose Electicvala   29       Diploma       Operator  Supervisor           8   
9             Sasna   26            BE       Software    Engineer           5   

   Salary                                             Adress PrefLocation  
0   12000  East Kadungallur, Near Uc Colleage Desom Ernak...    Ernakulam  
1   12000  Lakshmi Priya 7 / 39 B Muthu Vayal Kizhakkepur...    Ernakulam  
2   13000  Ledu Vilam, Parambil House, Near Kitchen Zaika...    Ernakulam  
3   35000  Munthottu House Vkt Po Tholakkal Kochi Bharath...     Thrissur  
4   35000  Vidhayathil House Attupuram Airoor Ernakulam A...    Ernakulam  
5   12000  Maithala Hoise,Kakkanad,Ekm Kakkanad Ernakulam...     Thrissur  
6   25000  Arphampattai House H M T Colony Kalamasheri Er...   Trivandrum  
7  100000     K.M.K Jn, N.Paravur Ezhikkara Ernakulam 683513    Ernakulam  
8   13000  Mg Road Near Shenoy Theatre Ernakulam College ...    Ernakulam  
9   15000  Triarch Hube Appartment 5 D Kanakerinagar Road...      Calicut

In [28]:
data.tail()

Name  Age Qualification         Stream      Title  \
83       Jesfy Joseph   24           BSc       Software  Developer   
84            Sanulal   25           MCA       Software  Developer   
85            Syamlal   27           BBA  Administratio  Executive   
86  Sreeram Devarajan   27           MBA  Administratio    Manager   
87           Usha Raj   25          MBBS       Medicine     Doctor   

    Experience  Salary                                             Adress  \
83           3   35000  Parattu House Thuruthu Aluva Aluva Ernakulam 6...   
84           4   35000      63/Nandanam Edapali Edapally Ernakulam 682024   
85           6   12000  Pattathil Ho Vidyanagar Kadavanthra Kadavantha...   
86           6   25000  Kalathilparambil House,Elamakara,Puthukalotam ...   
87           4   45000  Vadakedath House,Nethaji Road Aluva Aluva Erna...   

   PrefLocation  
83     Thrissur  
84     Thrissur  
85     Thrissur  
86     Thrissur  
87     Thrissur

In [32]:
data.loc[50]

Name                                                     Dg Prabhu
Age                                                             27
Qualification                                                  MBA
Stream                                               Administratio
Title                                                      Manager
Experience                                                       6
Salary                                                       25000
Adress           Prabhu Nivas,Ripublic Road N.Paravur Ezhikkara...
PrefLocation                                             Ernakulam
Name: 50, dtype: object

In [39]:
x=data.loc[[9,18,27],["Name","Stream","Experience"]] #syntax=data.loc[[rows],[colums]]
print(x)

            Name    Stream  Experience
9          Sasna  Software           5
18  Neetu Satish  Medicine           6
27       Mikhail  Operator           6


In [40]:
data.describe() #description of columns with numerical values

Age  Experience         Salary
count  88.000000   88.000000      88.000000
mean   24.943182    3.943182   23534.090909
std     2.178041    2.178041   14008.165815
min    21.000000    0.000000    8000.000000
25%    23.000000    2.000000   12000.000000
50%    25.000000    4.000000   25000.000000
75%    27.000000    6.000000   35000.000000
max    31.000000   10.000000  100000.000000

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Name           88 non-null     object
 1   Age            88 non-null     int64 
 2   Qualification  88 non-null     object
 3   Stream         88 non-null     object
 4   Title          88 non-null     object
 5   Experience     88 non-null     int64 
 6   Salary         88 non-null     int64 
 7   Adress         88 non-null     object
 8   PrefLocation   88 non-null     object
dtypes: int64(3), object(6)
memory usage: 6.3+ KB


In [42]:
data.dtypes

Name             object
Age               int64
Qualification    object
Stream           object
Title            object
Experience        int64
Salary            int64
Adress           object
PrefLocation     object
dtype: object

In [44]:
data['Experience'].max()

10

In [45]:
data.Salary.max()

100000

In [52]:
data[data["Experience"]==data.Experience.max()]

Name  Age Qualification    Stream   Title  Experience  Salary  \
7  Joshy Kuruvila   31          MBBS  Medicine  Doctor          10  100000   

                                           Adress PrefLocation  
7  K.M.K Jn, N.Paravur Ezhikkara Ernakulam 683513    Ernakulam

In [55]:
data[data["Experience"]==data.Experience.max()][["Name","Title"]]

Name   Title
7  Joshy Kuruvila  Doctor

In [57]:
data[data["Age"]==data.Age.min()][["Name","Age"]]

Name  Age
20  Kushil Aggarwal   21

In [61]:
num_row=data.shape[0]
print(type(num_row*7.9))
print(num_row)

<class 'float'>
88


In [ ]:
data.fillna(0) #set none/null values to 0

In [65]:
data.fillna({
    "Name": "NA",
    "Salary":0
})
#to set separate values to diff columns with null values

Name  Age Qualification         Stream      Title  \
0      Neon Prabhakar   22          Bcom       Commerce  Executive   
1    R Gopalakrishnan   23           BBA  Administratio  Executive   
2         Pratik Kala   22           LLB         Lawyer   Advocate   
3         Nanda Kumar   24           BSc       Software  Developer   
4           Siju John   25           MCA       Software  Developer   
..                ...  ...           ...            ...        ...   
83       Jesfy Joseph   24           BSc       Software  Developer   
84            Sanulal   25           MCA       Software  Developer   
85            Syamlal   27           BBA  Administratio  Executive   
86  Sreeram Devarajan   27           MBA  Administratio    Manager   
87           Usha Raj   25          MBBS       Medicine     Doctor   

    Experience  Salary                                             Adress  \
0            1   12000  East Kadungallur, Near Uc Colleage Desom Ernak...   
1            2   12000  Lakshmi Priya 7 / 39 B Muthu Vayal Kizhakkepur...   
2            1   13000  Ledu Vilam, Parambil House, Near Kitchen Zaika...   
3            3   35000  Munthottu House Vkt Po Tholakkal Kochi Bharath...   
4            4   35000  Vidhayathil House Attupuram Airoor Ernakulam A...   
..         ...     ...                                                ...   
83           3   35000  Parattu House Thuruthu Aluva Aluva Ernakulam 6...   
84           4   35000      63/Nandanam Edapali Edapally Ernakulam 682024   
85           6   12000  Pattathil Ho Vidyanagar Kadavanthra Kadavantha...   
86           6   25000  Kalathilparambil House,Elamakara,Puthukalotam ...   
87           4   45000  Vadakedath House,Nethaji Road Aluva Aluva Erna...   

   PrefLocation  
0     Ernakulam  
1     Ernakulam  
2     Ernakulam  
3      Thrissur  
4     Ernakulam  
..          ...  
83     Thrissur  
84     Thrissur  
85     Thrissur  
86     Thrissur  
87     Thrissur  

[88 rows x 9 columns]

In [66]:
g=data.groupby("Stream")

In [67]:
g

In [69]:
india=pd.DataFrame({
    'city':['mumbai','banglore','cochin'],
    'temp':[32,32,30]
    
})

us=pd.DataFrame({
    'city':['New York','Las Vegas','Sanfrancisco'],
    'temp':[20,21,34]
    
})

In [70]:
data.sort_index()

Name  Age Qualification         Stream      Title  \
0      Neon Prabhakar   22          Bcom       Commerce  Executive   
1    R Gopalakrishnan   23           BBA  Administratio  Executive   
2         Pratik Kala   22           LLB         Lawyer   Advocate   
3         Nanda Kumar   24           BSc       Software  Developer   
4           Siju John   25           MCA       Software  Developer   
..                ...  ...           ...            ...        ...   
83       Jesfy Joseph   24           BSc       Software  Developer   
84            Sanulal   25           MCA       Software  Developer   
85            Syamlal   27           BBA  Administratio  Executive   
86  Sreeram Devarajan   27           MBA  Administratio    Manager   
87           Usha Raj   25          MBBS       Medicine     Doctor   

    Experience  Salary                                             Adress  \
0            1   12000  East Kadungallur, Near Uc Colleage Desom Ernak...   
1            2   12000  Lakshmi Priya 7 / 39 B Muthu Vayal Kizhakkepur...   
2            1   13000  Ledu Vilam, Parambil House, Near Kitchen Zaika...   
3            3   35000  Munthottu House Vkt Po Tholakkal Kochi Bharath...   
4            4   35000  Vidhayathil House Attupuram Airoor Ernakulam A...   
..         ...     ...                                                ...   
83           3   35000  Parattu House Thuruthu Aluva Aluva Ernakulam 6...   
84           4   35000      63/Nandanam Edapali Edapally Ernakulam 682024   
85           6   12000  Pattathil Ho Vidyanagar Kadavanthra Kadavantha...   
86           6   25000  Kalathilparambil House,Elamakara,Puthukalotam ...   
87           4   45000  Vadakedath House,Nethaji Road Aluva Aluva Erna...   

   PrefLocation  
0     Ernakulam  
1     Ernakulam  
2     Ernakulam  
3      Thrissur  
4     Ernakulam  
..          ...  
83     Thrissur  
84     Thrissur  
85     Thrissur  
86     Thrissur  
87     Thrissur  

[88 rows x 9 columns]

Matplotlib

In [73]:
import matplotlib.pyplot as plt
%matplotlib  notebook
plt.get_backend()

'nbAgg'

In [89]:
plt.plot(4,5,"*")

In [92]:
import matplotlib.pyplot as plt
x=[0,9,8]
y=[8,5,6]
plt.plot(x,y,c='r')
plt.show

In [96]:
c=['google','amazon']
r=[100,897]
plt.bar(c,r)
plt.show

<function matplotlib.pyplot.show(block=None)>